/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.city;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import Hospital.City;
import Hospital.CityDirectory;
import Hospital.Community;
import Hospital.CommunityDirectory;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author dhruv
 */
public class AddCommunityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCommunityJPanel
     */
    JPanel workAreaJPanel;
    CityDirectory cityDirectory;
//    public AddCommunityJPanel() {
//        initComponents();
//    }

    AddCommunityJPanel(JPanel workAreaJPanel, CityDirectory cityDirectory) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.cityDirectory = cityDirectory;
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        txtCommunityName = new javax.swing.JTextField();
        btnSaveCommunity = new javax.swing.JButton();
        cmbCity = new javax.swing.JComboBox();
        lblCommunity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Community");

        lblCityName.setForeground(new java.awt.Color(0, 102, 102));
        lblCityName.setText("Select City");

        txtCommunityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCommunityNameKeyReleased(evt);
            }
        });

        btnSaveCommunity.setForeground(new java.awt.Color(0, 102, 102));
        btnSaveCommunity.setText("Save");
        btnSaveCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCommunityActionPerformed(evt);
            }
        });

        lblCommunity.setForeground(new java.awt.Color(0, 102, 102));
        lblCommunity.setText("Community Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveCommunity)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCommunity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCityName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCity, txtCommunityName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityName)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveCommunity)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCommunityActionPerformed
        // TODO add your handling code here:
        if (ValidFields()) {
            try {
                if (!(txtCommunityName.getText().matches("^[a-zA-Z]{1,30}$"))) {
                JOptionPane.showMessageDialog(this, "Please enter valid community name.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
                Community community = new Community();
                community.setName(txtCommunityName.getText());
                CommunityDirectory communityDir = ((City) cmbCity.getSelectedItem()).getCityData();
//                CommunityDirectory communityDir = new CommunityDirectory();
                community = communityDir.addCommunity(community);               
                if (community == null) {
                    JOptionPane.showMessageDialog(this, "Community already present", "Info", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please check the form data", "Info", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Community added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
            txtCommunityName.setText("");
        }
    }//GEN-LAST:event_btnSaveCommunityActionPerformed

    private void txtCommunityNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommunityNameKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-zA-Z]{1,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtCommunityName.getText());
        if (!match.matches()) {
            txtCommunityName.setBackground(Color.red);
        } else {
            txtCommunityName.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCommunityNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCommunity;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCommunityName;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
        cmbCity.removeAllItems();
        for (City s : cityDirectory.getCities()) {
            cmbCity.addItem(s);
        }
    }

    private boolean ValidFields() {
        if (!validField(txtCommunityName, "Please enter the community name")) {
            return false;
        }
        return true;
    }

    private boolean validField(JTextField fieldName, String errorMsg) {
        if (fieldName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, errorMsg);
            return false;
        }
        return true;
    }
}
