/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.city;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Hospital.CityDirectory;
import ui.MainScreen;

/**
 *
 * @author dhruv
 */
public class CityWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CityWorkAreaJPanel
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;

    public CityWorkAreaJPanel(JPanel mainWorkArea, CityDirectory cityDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBarJPanel = new javax.swing.JPanel();
        btnAddNewCity = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNewCommunity = new javax.swing.JButton();
        btnManageCity = new javax.swing.JButton();
        btnNewHouse = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(80);

        menuBarJPanel.setBackground(new java.awt.Color(204, 204, 255));

        btnAddNewCity.setForeground(new java.awt.Color(0, 102, 102));
        btnAddNewCity.setText("Add City");
        btnAddNewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCityActionPerformed(evt);
            }
        });

        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNewCommunity.setForeground(new java.awt.Color(0, 102, 102));
        btnNewCommunity.setText("Add Community");
        btnNewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCommunityActionPerformed(evt);
            }
        });

        btnManageCity.setForeground(new java.awt.Color(0, 102, 102));
        btnManageCity.setText("Manage City");
        btnManageCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCityActionPerformed(evt);
            }
        });

        btnNewHouse.setForeground(new java.awt.Color(0, 102, 102));
        btnNewHouse.setText("Add House");
        btnNewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPanelLayout = new javax.swing.GroupLayout(menuBarJPanel);
        menuBarJPanel.setLayout(menuBarJPanelLayout);
        menuBarJPanelLayout.setHorizontalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnAddNewCity)
                    .addComponent(btnNewCommunity)
                    .addComponent(btnNewHouse)
                    .addComponent(btnManageCity))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBarJPanelLayout.setVerticalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewCommunity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewHouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageCity)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(menuBarJPanel);

        workAreaJPanel.setBackground(new java.awt.Color(204, 204, 255));
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewHouseActionPerformed
        // TODO add your handling code here:
        if (cityDirectory.getCities().size() <= 0) {
            JOptionPane.showMessageDialog(this, "Please add city first", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AddHouseJPanel acjp = new AddHouseJPanel(workAreaJPanel, cityDirectory);
        workAreaJPanel.add("AddHouseJPanel", acjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnNewHouseActionPerformed

    private void btnManageCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCityActionPerformed
        // TODO add your handling code here:
        CityTableWorkAreaJPanel ctwajp = new CityTableWorkAreaJPanel(workAreaJPanel, cityDirectory);
        workAreaJPanel.add("CityTableWorkAreaJPanel", ctwajp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnManageCityActionPerformed

    private void btnNewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCommunityActionPerformed
        // TODO add your handling code here:
        if (this.cityDirectory.getCities().size() <= 0) {
            JOptionPane.showMessageDialog(this, "Please add city first", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AddCommunityJPanel acjp = new AddCommunityJPanel(workAreaJPanel, cityDirectory);
        workAreaJPanel.add("AddCityJPanel", acjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnNewCommunityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainScreen loginPanel = (MainScreen) component;
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddNewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCityActionPerformed
        // TODO add your handling code here:
        AddCityJPanel acjp = new AddCityJPanel(workAreaJPanel, cityDirectory);
        workAreaJPanel.add("AddCityJPanel", acjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnAddNewCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCity;
    private javax.swing.JButton btnBack;
    protected static javax.swing.JButton btnManageCity;
    protected static javax.swing.JButton btnNewCommunity;
    protected static javax.swing.JButton btnNewHouse;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuBarJPanel;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
