/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.doctor;

import Hospital.City;
import Hospital.CityDirectory;
import Hospital.Community;
import Hospital.Doctor;
import Hospital.DoctorDirectory;
import Hospital.Patient;
import Hospital.PatientDirectory;
import Hospital.Person;
import Hospital.PersonDirectory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhruv
 */
public class AddDoctorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctorDetailsJPanel
     */
    JPanel workAreaJPanel;
    CityDirectory cityDirectory;
    DoctorDirectory doctorDirectory;
    Doctor doctorInfo;
    
    public AddDoctorDetailsJPanel(JPanel workAreaJPanel, CityDirectory cityDirectory, DoctorDirectory doctorDirectory) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.cityDirectory = cityDirectory;
        this.doctorDirectory = doctorDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSpeciality = new javax.swing.JLabel();
        btnSearchPatient = new javax.swing.JButton();
        txtSsn = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txt_Speciality = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblDateErr = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbCommunity = new javax.swing.JComboBox<>();
        lblCity = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        cmbHospital = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 102, 102));

        lblSpeciality.setForeground(new java.awt.Color(0, 102, 102));
        lblSpeciality.setText("Speciality");

        btnSearchPatient.setForeground(new java.awt.Color(0, 102, 102));
        btnSearchPatient.setText("Search Doctor");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        lblSsn.setForeground(new java.awt.Color(0, 102, 102));
        lblSsn.setText("SSN");

        lblCommunity.setForeground(new java.awt.Color(0, 102, 102));
        lblCommunity.setText("Community");

        lblLastName.setForeground(new java.awt.Color(0, 102, 102));
        lblLastName.setText("Last Name");

        lblDateErr.setForeground(new java.awt.Color(255, 0, 0));

        txtLastName.setEnabled(false);

        txtFirstName.setEnabled(false);

        lblFirstName.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName.setText("First Name");

        lblHospital.setForeground(new java.awt.Color(0, 102, 102));
        lblHospital.setText("Hospital");

        lblAge.setForeground(new java.awt.Color(0, 102, 102));
        lblAge.setText("Age");

        btnSave.setForeground(new java.awt.Color(0, 102, 102));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAge.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Add Doctor Details");

        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setText("City");

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Virginia", " " }));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        cmbHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America Cancer Hospital", "Harvard Hospital", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblSpeciality)
                            .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearchPatient))
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(347, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Speciality, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(cmbHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity)
                                    .addComponent(lblCommunity))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(564, 564, 564)
                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeciality)
                    .addComponent(txt_Speciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospital)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCommunity)
                    .addComponent(cmbCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
       Doctor doctor = DoctorDirectory.searchDoctor(txtSsn.getText());
        //DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        doctorInfo = doctor;
        if (doctorInfo == null) {
            List<City> cities = cityDirectory.getCities();

            List<Person> people = PersonDirectory.getPeople();
            for (Person person : people) {
                if (txtSsn.getText() == null ? String.valueOf(person.getSocialSecurityNum()) == null : txtSsn.getText().equals(String.valueOf(person.getSocialSecurityNum()))) {
                    doctorInfo = new Doctor();
                    doctorInfo.setSocialSecurityNum(person.getSocialSecurityNum());
                    doctorInfo.setFirstName(person.getFirstName());
                    doctorInfo.setLastName(person.getLastName());
                    doctorInfo.setGender(person.getGender());
                    doctorInfo.setAge(person.getAge());
                    doctorInfo.setEmail(person.getEmail());
                    doctorInfo.setPersonPicture(person.getPersonPicture());
                    txtFirstName.setText(doctorInfo.getFirstName());
                    txtLastName.setText(doctorInfo.getLastName());
                    //txtPatientDob.setText(dateFormat.format(patientInfo.getDob()));
                    txtAge.setText(String.valueOf(doctorInfo.getAge()));
                    DoctorDirectory.addDoctor(doctorInfo);
                    return;
                }
            }
            if (doctorInfo == null) {
                JOptionPane.showMessageDialog(this, "SSN number did not match wth any person", "Info", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            this.doctorInfo = doctor;
            txtFirstName.setText(doctorInfo.getFirstName());
            txtLastName.setText(doctorInfo.getLastName());
            //txtPatientDob.setText(dateFormat.format(patientInfo.getDob()));
            txtAge.setText(String.valueOf(doctorInfo.getAge()));
        }
              
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       int SSN = Integer.parseInt(txtSsn.getText());
       String Firstname = txtFirstName.getText();
       String LastName = txtLastName.getText();
       int Age = Integer.parseInt(txtAge.getText());
       String speciality = txt_Speciality.getText();
       String Hospital = cmbHospital.getSelectedItem().toString();
       String City = cmbCity.getSelectedItem().toString();
       String Community = cmbCommunity.getSelectedItem().toString();
       
       Doctor doctor = doctorDirectory.addnewDoctor();
       
       doctor.setSocialSecurityNum(SSN);
       doctor.setFirstName(Firstname);
       doctor.setLastName(LastName);
       doctor.setAge(Age);
       doctor.setSpeciality(speciality);
       doctor.setHospital(Hospital);
       doctor.setdocCommunity(Community);
       
       JOptionPane.showMessageDialog(this, "New Doctor Details added successfully!");
       
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
         
        if(cmbCity.getSelectedItem().equals("Boston")){
            cmbCommunity.removeAllItems();
            cmbCommunity.addItem("Bolyston Street");
            cmbCommunity.addItem("Park Drive");
            cmbCommunity.setSelectedItem(null);
            
        }
        else if(cmbCity.getSelectedItem().equals("Virginia")){
            cmbCommunity.removeAllItems();
            cmbCommunity.addItem("Richmond");
            cmbCommunity.addItem("Alexandria");
            cmbCommunity.setSelectedItem(null);
        }

    }//GEN-LAST:event_cmbCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbCommunity;
    private javax.swing.JComboBox<String> cmbHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDateErr;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txt_Speciality;
    // End of variables declaration//GEN-END:variables
 
    
    
    private void populateCityCombo() {
        
       String[] s= (String[]) cityDirectory.getCities().toArray();
       DefaultComboBoxModel dm= new DefaultComboBoxModel(s);
       cmbCity.setModel(dm);
    }

}
