/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.person;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import Hospital.City;
import Hospital.CityDirectory;
import Hospital.Community;
import Hospital.CommunityDirectory;
import Hospital.House;
import Hospital.Person;
import Hospital.PersonDirectory;

/**
 *
 * @author dhruv
 */
public class AddPersonInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPersonInfoJPanel
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
//    public AddPersonInfoJPanel() {
//        initComponents();
//    }

    public AddPersonInfoJPanel(JPanel mainWorkArea, CityDirectory cityDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
        populateCityCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCityName = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbCommunity = new javax.swing.JComboBox();
        btnSavePerson = new javax.swing.JButton();
        lblPDemographics = new javax.swing.JLabel();
        lblPFirstName = new javax.swing.JLabel();
        lblPLastName = new javax.swing.JLabel();
        lblPPhoneNum = new javax.swing.JLabel();
        lblPHeight = new javax.swing.JLabel();
        lblPAge = new javax.swing.JLabel();
        lblPWeight = new javax.swing.JLabel();
        lblPSsn = new javax.swing.JLabel();
        txtPFirstName = new javax.swing.JTextField();
        txtPLastName = new javax.swing.JTextField();
        txtPPhoneNum = new javax.swing.JTextField();
        txtPAge = new javax.swing.JTextField();
        txtPWeight = new javax.swing.JTextField();
        txtPHeight = new javax.swing.JTextField();
        lblPFirstNameErr = new javax.swing.JLabel();
        lblPLastNameErr = new javax.swing.JLabel();
        lblPPhoneNumErr = new javax.swing.JLabel();
        lblPAgeErr = new javax.swing.JLabel();
        lblPHeightErr = new javax.swing.JLabel();
        lblPWeightErr = new javax.swing.JLabel();
        lblPSsnErr = new javax.swing.JLabel();
        txtPSsn = new javax.swing.JFormattedTextField();
        lblPDobErr = new javax.swing.JLabel();
        lblPHouseName = new javax.swing.JLabel();
        txtPHouseName = new javax.swing.JTextField();
        btnUploadPersonPic = new javax.swing.JButton();
        lblPersonPicture = new javax.swing.JLabel();

        lblCityName.setText("Select City");

        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Community");

        cmbCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCommunityActionPerformed(evt);
            }
        });

        btnSavePerson.setText("Save");
        btnSavePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePersonActionPerformed(evt);
            }
        });

        lblPDemographics.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        lblPDemographics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPDemographics.setText("Person Demographics");

        lblPFirstName.setText("First Name");

        lblPLastName.setText("Last Name");

        lblPPhoneNum.setText("Phone Number");

        lblPHeight.setText("Height");

        lblPAge.setText("Age");

        lblPWeight.setText("Weight");

        lblPSsn.setText("Social security number");

        txtPFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPFirstNameActionPerformed(evt);
            }
        });
        txtPFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPFirstNameKeyReleased(evt);
            }
        });

        txtPLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPLastNameActionPerformed(evt);
            }
        });
        txtPLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPLastNameKeyReleased(evt);
            }
        });

        txtPPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPhoneNumActionPerformed(evt);
            }
        });
        txtPPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPPhoneNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPPhoneNumKeyReleased(evt);
            }
        });

        txtPAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAgeActionPerformed(evt);
            }
        });
        txtPAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPAgeKeyReleased(evt);
            }
        });

        txtPWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPWeightActionPerformed(evt);
            }
        });
        txtPWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPWeightKeyReleased(evt);
            }
        });

        txtPHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPHeightActionPerformed(evt);
            }
        });

        lblPFirstNameErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPLastNameErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPPhoneNumErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPAgeErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPHeightErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPWeightErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPSsnErr.setForeground(new java.awt.Color(255, 0, 0));

        try {
            txtPSsn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPSsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPSsnKeyReleased(evt);
            }
        });

        lblPDobErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPHouseName.setText("House Name");

        txtPHouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPHouseNameActionPerformed(evt);
            }
        });
        txtPHouseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPHouseNameKeyReleased(evt);
            }
        });

        btnUploadPersonPic.setText("Upload Picture");
        btnUploadPersonPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPersonPicActionPerformed(evt);
            }
        });

        lblPersonPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDemographics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSavePerson)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnUploadPersonPic)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPAge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPHouseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblPFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPPhoneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCommunity, 0, 137, Short.MAX_VALUE)
                            .addComponent(cmbCity, 0, 137, Short.MAX_VALUE)
                            .addComponent(txtPAge)
                            .addComponent(txtPHeight)
                            .addComponent(txtPWeight)
                            .addComponent(txtPSsn)
                            .addComponent(txtPHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPFirstName)
                            .addComponent(txtPLastName)
                            .addComponent(txtPPhoneNum))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPFirstNameErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPLastNameErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPPhoneNumErr, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(lblPAgeErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPHeightErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPWeightErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPSsnErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPDobErr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCity, cmbCommunity, txtPAge, txtPFirstName, txtPHeight, txtPHouseName, txtPLastName, txtPPhoneNum, txtPSsn, txtPWeight});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, lblCityName, lblPAge, lblPFirstName, lblPHeight, lblPHouseName, lblPLastName, lblPPhoneNum, lblPSsn, lblPWeight});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblPDemographics)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPersonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUploadPersonPic))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCityName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPFirstNameErr))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPLastNameErr))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPPhoneNumErr))))
                                .addGap(28, 28, 28))
                            .addComponent(lblPDobErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPAgeErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPHeightErr))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPWeightErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPSsnErr)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28)
                .addComponent(btnSavePerson)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, lblCityName, lblPAge, lblPFirstName, lblPHeight, lblPHouseName, lblPLastName, lblPPhoneNum, lblPSsn, lblPWeight});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbCity, cmbCommunity, txtPAge, txtPFirstName, txtPHeight, txtPHouseName, txtPLastName, txtPPhoneNum, txtPSsn, txtPWeight});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePersonActionPerformed
        // TODO add your handling code here:

        int phoneNum;
        int age;
        int socialSecNum;
        double height;
        double weight;
        Date dob;
        Person personDemographics = new Person();
        if (((City) cmbCity.getSelectedItem()) == null) {
            JOptionPane.showMessageDialog(this, "City not present", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (((Community) cmbCommunity.getSelectedItem()) == null) {
            JOptionPane.showMessageDialog(this, "Community not present int he city", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (ValidFields()) {
            
                phoneNum = Integer.parseInt(txtPPhoneNum.getText());
                age = Integer.parseInt(txtPAge.getText());
                socialSecNum = Integer.parseInt(txtPSsn.getText().replace("-", ""));

                height = Double.parseDouble(txtPHeight.getText());
                weight = Double.parseDouble(txtPWeight.getText());
                //dob = txtPDob.getDate();
                ImageIcon myIcon = (ImageIcon) lblPersonPicture.getIcon();
                if(myIcon == null) {
                    JOptionPane.showMessageDialog(this, "Please add person picture", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
                personDemographics.setPersonPicture((Image) myIcon.getImage());
         
            
            if (!(txtPFirstName.getText().matches("^[a-zA-Z]*$"))) {
                JOptionPane.showMessageDialog(this, "Please enter valid first name. First name can only contain alphabets", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else if (!(txtPLastName.getText().matches("^[a-zA-Z]*$"))) {
                JOptionPane.showMessageDialog(this, "Please enter valid last name. Last name can only contain alphabets", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            personDemographics.setFirstName(txtPFirstName.getText());
            personDemographics.setLastName(txtPLastName.getText());
            personDemographics.setPhoneNumber(phoneNum);
            //personDemographics.setDob(dob);
            personDemographics.setAge(age);
            personDemographics.setHeight(height);
            personDemographics.setWeight(weight);
            personDemographics.setSocialSecurityNum(socialSecNum);

            House house = ((House) ((Community) cmbCommunity.getSelectedItem()).getEnteredHouse(txtPHouseName.getText()));

            if (house == null) {
                JOptionPane.showMessageDialog(this, "House not present in the community", "Info", JOptionPane.WARNING_MESSAGE);
                return;
            }
            personDemographics = house.addHousePerson(personDemographics);
            if(personDemographics != null) {
                PersonDirectory.addPerson(personDemographics);
            }

            if (personDemographics == null) {
                JOptionPane.showMessageDialog(this, "Person woth same Social security number already present", "Info", JOptionPane.WARNING_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Person demographics added");
        }
    }//GEN-LAST:event_btnSavePersonActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
        populateCommunityCombo();
    }//GEN-LAST:event_cmbCityActionPerformed

    private void txtPFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPFirstNameKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-zA-Z]{1,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtPFirstName.getText());
        if (!match.matches()) {
            lblPFirstNameErr.setText("Incorrect firstname");
            //            lblPLastNameErr.setText("Incorrect firstname");
            //            lblPHeightErr.setText("Incorrect firstname");
            //            lblPPhoneNumErr.setText("Incorrect firstname");
            //            lblPWeightErr.setText("Incorrect firstname");
            //            lblPDobErr.setText("Incorrect firstname");
            //            lblPSsnErr.setText("Incorrect firstname");
            //            lblPAgeErr.setText("Incorrect firstname");

        } else {
            lblPFirstNameErr.setText(null);
        }
    }//GEN-LAST:event_txtPFirstNameKeyReleased

    private void txtPFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPFirstNameActionPerformed

    private void txtPLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPLastNameKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-zA-Z]{1,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtPLastName.getText());
        if (!match.matches()) {
            lblPLastNameErr.setText("Incorrect last name");
        } else {
            lblPLastNameErr.setText(null);
        }
    }//GEN-LAST:event_txtPLastNameKeyReleased

    private void txtPLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPLastNameActionPerformed

    private void txtPAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPAgeKeyReleased
        // TODO add your handling code here:
        String agePattern = "\\d{1,3}";
        Pattern patt = Pattern.compile(agePattern);
        Matcher match = patt.matcher(txtPAge.getText());
        if (!match.matches()) {
            lblPAgeErr.setText("Incorrect age");
        } else {
            lblPAgeErr.setText(null);
        }
    }//GEN-LAST:event_txtPAgeKeyReleased

    private void txtPAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAgeKeyPressed

    private void txtPAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAgeActionPerformed

    private void txtPPhoneNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPhoneNumKeyReleased
        // TODO add your handling code here:
        //        String value = txtPPhoneNum.getText();
        //        int length = value.length();
        //        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || ((evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyCode() == KeyEvent.VK_DELETE)) ) {
        //            txtPPhoneNum.setEditable(true);
        //            lblPPhoneNum.setText("");
        //        } else {
        //            txtPPhoneNum.setEditable(false);
        ////            lblPPhoneNum.setText("Enter only numeric digits(0-9)");
        //        }

        //        String pattern = "^[0-9]{0,12}$";
        //        Pattern patt = Pattern.compile(pattern);
        //        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || ((evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyCode() == KeyEvent.VK_DELETE)) ) {
        //            txtPPhoneNum.setEditable(true);
        //        } else {
        //            txtPPhoneNum.setEditable(false);
        //        }
        //        Matcher match = patt.matcher(txtPPhoneNum.getText());
        //        if(!match.matches()) {
        //            lblPPhoneNumErr.setText("Incorrect phone number");
        //        } else {
        //            lblPPhoneNumErr.setText(null);
        //        }
        String phonePattern = "\\d{0,12}";
        Pattern patt = Pattern.compile(phonePattern);
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || ((evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyCode() == KeyEvent.VK_DELETE))) {
            txtPPhoneNum.setEditable(true);
        } else {
            txtPPhoneNum.setEditable(false);
        }
        Matcher match = patt.matcher(txtPPhoneNum.getText());
        if (!match.matches()) {
            lblPPhoneNumErr.setText("Incorrect phone number");
        } else {
            lblPPhoneNumErr.setText(null);
        }
    }//GEN-LAST:event_txtPPhoneNumKeyReleased

    private void txtPPhoneNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPhoneNumKeyPressed
        // TODO add your handling code here:
        //        String pattern = "^[0-9]{0,12}$";
    }//GEN-LAST:event_txtPPhoneNumKeyPressed

    private void txtPPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPhoneNumActionPerformed

    private void txtPWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPWeightKeyReleased
        // TODO add your handling code here:
        String pattern = "^[-?\\d+(\\.\\d+)?]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtPWeight.getText());
        if (!match.matches()) {
            lblPWeightErr.setText("Incorrect weight format");
        } else {
            lblPWeightErr.setText(null);
        }
    }//GEN-LAST:event_txtPWeightKeyReleased

    private void txtPWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPWeightActionPerformed

    private void txtPHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPHeightActionPerformed

    private void txtPSsnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPSsnKeyReleased
        // TODO add your handling code here:
        String regex = "^(?!666|000|9\\d{2})\\d{3}"
                + "-(?!00)\\d{2}-"
                + "(?!0{4})\\d{4}$";
        Pattern patt = Pattern.compile(regex);
        Matcher match = patt.matcher(txtPSsn.getText());
        if (!match.matches()) {
            lblPSsnErr.setText("Incorrect social security number");
        } else {
            lblPSsnErr.setText(null);
        }
    }//GEN-LAST:event_txtPSsnKeyReleased

    private void txtPHouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPHouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPHouseNameActionPerformed

    private void txtPHouseNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPHouseNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPHouseNameKeyReleased

    private void btnUploadPersonPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPersonPicActionPerformed
        // TODO add your handling code here:
        JFileChooser browseDriverLicenseFile = new JFileChooser();

        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseDriverLicenseFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseDriverLicenseFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseDriverLicenseFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();

            //Display image in JLable
            ImageIcon Ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = Ii.getImage().getScaledInstance(lblPersonPicture.getWidth(), lblPersonPicture.getHeight(), Image.SCALE_SMOOTH);
            lblPersonPicture.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btnUploadPersonPicActionPerformed

    private void cmbCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePerson;
    private javax.swing.JButton btnUploadPersonPic;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JComboBox cmbCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblPAge;
    private javax.swing.JLabel lblPAgeErr;
    private javax.swing.JLabel lblPDemographics;
    private javax.swing.JLabel lblPDobErr;
    private javax.swing.JLabel lblPFirstName;
    private javax.swing.JLabel lblPFirstNameErr;
    private javax.swing.JLabel lblPHeight;
    private javax.swing.JLabel lblPHeightErr;
    private javax.swing.JLabel lblPHouseName;
    private javax.swing.JLabel lblPLastName;
    private javax.swing.JLabel lblPLastNameErr;
    private javax.swing.JLabel lblPPhoneNum;
    private javax.swing.JLabel lblPPhoneNumErr;
    private javax.swing.JLabel lblPSsn;
    private javax.swing.JLabel lblPSsnErr;
    private javax.swing.JLabel lblPWeight;
    private javax.swing.JLabel lblPWeightErr;
    private javax.swing.JLabel lblPersonPicture;
    private javax.swing.JTextField txtPAge;
    private javax.swing.JTextField txtPFirstName;
    private javax.swing.JTextField txtPHeight;
    private javax.swing.JTextField txtPHouseName;
    private javax.swing.JTextField txtPLastName;
    private javax.swing.JTextField txtPPhoneNum;
    private javax.swing.JFormattedTextField txtPSsn;
    private javax.swing.JTextField txtPWeight;
    // End of variables declaration//GEN-END:variables

    public void populateCityCombo() {
        cmbCity.removeAllItems();
        for (City s : cityDirectory.getCities()) {
            cmbCity.addItem(s);
        }
    }

    private void populateCommunityCombo() {
        cmbCommunity.removeAllItems();
        if (cmbCity.getSelectedItem() != null) {
            for (Community s : ((City) cmbCity.getSelectedItem()).getCityData().getCommunities()) {
                cmbCommunity.addItem(s);
            }
        }
    }

    private boolean ValidFields() {
        if (!validField(txtPFirstName, "Please enter the first name")) {
            return false;
        } else if (!validField(txtPLastName, "Please enter the last name")) {
            return false;
        } else if (!validField(txtPPhoneNum, "Please enter the phone number")) {
            return false;
         //else if (txtPDob.getDate() == null) {
            //JOptionPane.showMessageDialog(this, "Please enter the date of birth");
            //return false;
        } else if (!validField(txtPAge, "Please enter the age")) {
            return false;
        } else if (!validField(txtPHeight, "Please enter the height")) {
            return false;
        } else if (!validField(txtPWeight, "Please enter the weight")) {
            return false;
        } else if (txtPSsn.getText().replace("-", "").trim().length() == 0) {//(!validField( txtPSsn, "Please enter the Social security number")) {
            JOptionPane.showMessageDialog(this, "Please enter the Social security number");
            return false;
        }
        return true;
    }

    private boolean validField(JTextField fieldName, String errorMsg) {
        if (fieldName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, errorMsg);
            return false;
        }
        return true;
    }
}
