/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import Hospital.City;
import Hospital.CityDirectory;
import Hospital.EncounterHistory;
import Hospital.Patient;
import Hospital.PatientDirectory;
import Hospital.Person;
import Hospital.PersonDirectory;
import Hospital.VitalSigns;
import java.awt.Color;

/**
 *
 * @author dhruv
 */
public class AddPatientVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientVitalSignsJPanel
     */
    JPanel workAreaJPanel;
    CityDirectory cityDirectory;
    PatientDirectory patientDirectory;
    Patient patientInfo;
//    public AddPatientVitalSignsJPanel() {
//        initComponents();
//    }

    AddPatientVitalSignsJPanel(JPanel workAreaJPanel, CityDirectory cityDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.cityDirectory = cityDirectory;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPulse = new javax.swing.JTextField();
        txtPressure = new javax.swing.JTextField();
        lblDateErr = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        lblPulseErr = new javax.swing.JLabel();
        lblBPErr = new javax.swing.JLabel();
        lblTempErr = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblPressure = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        btnSearchPatient = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtPatientAge = new javax.swing.JTextField();
        lblPatientAge = new javax.swing.JLabel();
        lblOxygen = new javax.swing.JLabel();
        txtOxygen = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        txtPulse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPulseKeyReleased(evt);
            }
        });

        txtPressure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPressureKeyReleased(evt);
            }
        });

        lblDateErr.setForeground(new java.awt.Color(255, 0, 0));

        lblPulse.setForeground(new java.awt.Color(0, 102, 102));
        lblPulse.setText("Pulse Rate");

        txtTemperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTemperatureKeyReleased(evt);
            }
        });

        lblPulseErr.setForeground(new java.awt.Color(255, 0, 0));

        lblBPErr.setForeground(new java.awt.Color(255, 0, 0));

        lblTempErr.setForeground(new java.awt.Color(255, 0, 0));

        lblTemperature.setForeground(new java.awt.Color(0, 102, 102));
        lblTemperature.setText("Temperature");

        btnSave.setForeground(new java.awt.Color(0, 102, 102));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPressure.setForeground(new java.awt.Color(0, 102, 102));
        lblPressure.setText("Blood Pressure");

        lblFirstName.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName.setText("First Name");

        txtFirstName.setEnabled(false);

        txtLastName.setEnabled(false);

        lblLastName.setForeground(new java.awt.Color(0, 102, 102));
        lblLastName.setText("Last Name");

        lblSsn.setForeground(new java.awt.Color(0, 102, 102));
        lblSsn.setText("SSN");

        btnSearchPatient.setForeground(new java.awt.Color(0, 102, 102));
        btnSearchPatient.setText("Search Patient");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add patient Vitals");

        txtPatientAge.setEnabled(false);

        lblPatientAge.setForeground(new java.awt.Color(0, 102, 102));
        lblPatientAge.setText("Age");

        lblOxygen.setForeground(new java.awt.Color(0, 102, 102));
        lblOxygen.setText("Oxygen");

        lblDate.setForeground(new java.awt.Color(0, 102, 102));
        lblDate.setText("Date");

        txtDate.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(407, 407, 407)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBPErr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTempErr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDate)
                                    .addGap(96, 96, 96)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(252, 252, 252)
                                    .addComponent(lblPulseErr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPatientAge, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(lblPulse, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(lblOxygen, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearchPatient))
                                    .addComponent(txtFirstName)
                                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFirstName, txtLastName, txtPressure, txtPulse, txtTemperature});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFirstName, lblLastName, lblPressure, lblPulse, lblTemperature});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientAge)
                    .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPressure)
                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblBPErr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPulseErr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTempErr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOxygen)
                            .addComponent(txtOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addGap(76, 76, 76))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFirstName, lblLastName, lblPressure, lblPulse, lblTemperature});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
        Patient patient = PatientDirectory.searchPatient(txtSsn.getText());
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        patientInfo = patient;
        if (patientInfo == null) {
            List<City> cities = cityDirectory.getCities();

            List<Person> people = PersonDirectory.getPeople();
            for (Person person : people) {
                if (txtSsn.getText() == null ? String.valueOf(person.getSocialSecurityNum()) == null : txtSsn.getText().equals(String.valueOf(person.getSocialSecurityNum()))) {
                    patientInfo = new Patient();
                    patientInfo.setSocialSecurityNum(person.getSocialSecurityNum());
                    patientInfo.setFirstName(person.getFirstName());
                    patientInfo.setLastName(person.getLastName());
                    patientInfo.setAge(person.getAge());
                    patientInfo.setPersonPicture(person.getPersonPicture());
                    
                    txtFirstName.setText(patientInfo.getFirstName());
                    txtLastName.setText(patientInfo.getLastName());
                    txtPatientAge.setText(String.valueOf(patientInfo.getAge()));
                    PatientDirectory.addPatient(patientInfo);
                    return;
                }
            }
            if (patientInfo == null) {
                JOptionPane.showMessageDialog(this, "SSN number did not match wth any person", "Info", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            this.patientInfo = patient;
            txtFirstName.setText(patientInfo.getFirstName());
            txtLastName.setText(patientInfo.getLastName());
            txtPatientAge.setText(String.valueOf(patientInfo.getAge()));
        }
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void txtPulseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPulseKeyReleased
        // TODO add your handling code here:
        String agePattern = "\\d{1,3}";
        Pattern patt = Pattern.compile(agePattern);
        Matcher match = patt.matcher(txtPulse.getText());
        if (!match.matches()) {
            //lblPulseErr.setText("Incorrect pulse format");
            txtPulse.setBackground(Color.red);
        } else {
            lblPulseErr.setText(null);
            txtPulse.setBackground(null);
        }
    }//GEN-LAST:event_txtPulseKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        double temperature;
        double pressure;
        int pulse;
        int oxygen;
        String date = txtDate.getText();
        
        if (patientInfo == null) {
            JOptionPane.showMessageDialog(this, "Invalid patient", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (txtSsn.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please check social security number", "Info", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (ValidFields()) {
            try {
                temperature = Double.parseDouble(txtTemperature.getText());
                pressure = Double.parseDouble(txtPressure.getText());
                pulse = Integer.parseInt(txtPulse.getText());
                oxygen = Integer.parseInt(txtOxygen.getText());
                if (lblPulseErr.getText() != null && lblPulseErr.getText().trim().length() != 0) {
                    JOptionPane.showMessageDialog(this, "Please enter 3 digit pulse rate", "Info", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please check the form data", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            VitalSigns vs = ((EncounterHistory) patientInfo.getEncounterHistory()).addnewVitals();

            vs.setTemperature(temperature);
            vs.setBloodPressure(pressure);
            vs.setPulse(pulse);
            vs.setOxygen(oxygen);
            vs.setDate(date);
            
            JOptionPane.showMessageDialog(this, "New Vital Signs added");
            txtSsn.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtPatientAge.setText("");
            txtTemperature.setText("");
            txtPressure.setText("");
            txtPulse.setText("");
            txtDate.setText("");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTemperatureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemperatureKeyReleased
        // TODO add your handling code here:
        String pattern = "^[-?\\d+(\\.\\d+)?]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtTemperature.getText());
        if (!match.matches()) {
            //lblTempErr.setText("Incorrect temerature format");
            txtTemperature.setBackground(Color.red);
        } else {
            lblTempErr.setText(null);
            txtTemperature.setBackground(null);
        }
    }//GEN-LAST:event_txtTemperatureKeyReleased

    private void txtPressureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPressureKeyReleased
        // TODO add your handling code here:
        String pattern = "^[-?\\d+(\\.\\d+)?]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(txtPressure.getText());
        if (!match.matches()) {
            //lblBPErr.setText("Incorrect blood pressure format");
            txtPressure.setBackground(Color.red);
        } else {
            lblBPErr.setText(null);
            txtPressure.setBackground(null);
        }
    }//GEN-LAST:event_txtPressureKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JLabel lblBPErr;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateErr;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOxygen;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblPulseErr;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTempErr;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOxygen;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPressure;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
    private boolean ValidFields() {
        if (!validField(txtTemperature, "Please enter the temperature")) {
            return false;
        } else if (!validField(txtPressure, "Please enter the blood pressure")) {
            return false;
        } else if (!validField(txtPulse, "Please enter the pulse")) {
            return false;
        }
        return true;
    }

    private boolean validField(JTextField fieldName, String errorMsg) {
        if (fieldName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, errorMsg);
            return false;
        }
        return true;
    }
}
