/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Hospital.CityDirectory;
import Hospital.PatientDirectory;
import ui.MainScreen;

/**
 *
 * @author dhruv
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
    PatientDirectory patientDirectory;
//    public PatientWorkAreaJPanel() {
//        initComponents();
//    }

    public PatientWorkAreaJPanel(JPanel mainWorkArea, CityDirectory cityDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workAreaJPanel = new javax.swing.JPanel();
        menuBarJPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnAddPatientVital = new javax.swing.JButton();
        btnViewPatientHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));

        jSplitPane1.setDividerLocation(80);

        workAreaJPanel.setBackground(new java.awt.Color(204, 204, 255));
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        menuBarJPanel.setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddPatientVital.setForeground(new java.awt.Color(0, 102, 102));
        btnAddPatientVital.setText("Add Vitals");
        btnAddPatientVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientVitalActionPerformed(evt);
            }
        });

        btnViewPatientHistory.setForeground(new java.awt.Color(0, 102, 102));
        btnViewPatientHistory.setText("View History");
        btnViewPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPanelLayout = new javax.swing.GroupLayout(menuBarJPanel);
        menuBarJPanel.setLayout(menuBarJPanelLayout);
        menuBarJPanelLayout.setHorizontalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuBarJPanelLayout.createSequentialGroup()
                        .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnAddPatientVital, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuBarJPanelLayout.setVerticalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPatientVital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPatientHistory)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuBarJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientVitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientVitalActionPerformed
        // TODO add your handling code here:
        AddPatientVitalSignsJPanel apvsjp = new AddPatientVitalSignsJPanel(workAreaJPanel, cityDirectory, patientDirectory);
        workAreaJPanel.add("AddPatientVitalSignsJPanel", apvsjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnAddPatientVitalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //        MainScreen loginScreen = new MainScreen(mainWorkArea, cityDirectory);
        //        mainWorkArea.add("MainScreen", loginScreen);
        //        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        //        layout.next(mainWorkArea);

        mainWorkArea.remove(this);

        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainScreen loginPanel = (MainScreen) component;
        //        loginPanel.populateSupplierCombo();

        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientHistoryActionPerformed
        // TODO add your handling code here:
        PatientTableJPanel ptjp = new PatientTableJPanel(workAreaJPanel, cityDirectory, patientDirectory);
        workAreaJPanel.add("PatientTableJPanel", ptjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnViewPatientHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatientVital;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewPatientHistory;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuBarJPanel;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
