/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Hospital.CityDirectory;
import Hospital.PatientDirectory;
import ui.LoginScreen;

/**
 *
 * @author dhruv
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
    PatientDirectory patientDirectory;
//    public PatientWorkAreaJPanel() {
//        initComponents();
//    }

    public PatientWorkAreaJPanel(JPanel mainWorkArea, CityDirectory cityDirectory, PatientDirectory patientDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBarJPanel = new javax.swing.JPanel();
        btnAddPatientVital = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewPatientHistory = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnAddPatientVital.setText("Add Patient Vital Signs");
        btnAddPatientVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientVitalActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewPatientHistory.setText("View Patient History");
        btnViewPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPanelLayout = new javax.swing.GroupLayout(menuBarJPanel);
        menuBarJPanel.setLayout(menuBarJPanelLayout);
        menuBarJPanelLayout.setHorizontalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPatientVital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPatientHistory)
                .addGap(140, 140, 140))
        );
        menuBarJPanelLayout.setVerticalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatientVital)
                    .addComponent(btnBack)
                    .addComponent(btnViewPatientHistory))
                .addGap(27, 27, 27))
        );

        jSplitPane1.setTopComponent(menuBarJPanel);

        workAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientVitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientVitalActionPerformed
        // TODO add your handling code here:
        AddPatientVitalSignsJPanel apvsjp = new AddPatientVitalSignsJPanel(workAreaJPanel, cityDirectory, patientDirectory);
        workAreaJPanel.add("AddPatientVitalSignsJPanel", apvsjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnAddPatientVitalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //        LoginScreen loginScreen = new LoginScreen(mainWorkArea, cityDirectory);
        //        mainWorkArea.add("LoginScreen", loginScreen);
        //        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        //        layout.next(mainWorkArea);

        mainWorkArea.remove(this);

        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LoginScreen loginPanel = (LoginScreen) component;
        //        loginPanel.populateSupplierCombo();

        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientHistoryActionPerformed
        // TODO add your handling code here:
        PatientTableJPanel ptjp = new PatientTableJPanel(workAreaJPanel, cityDirectory, patientDirectory);
        workAreaJPanel.add("PatientTableJPanel", ptjp);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnViewPatientHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatientVital;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewPatientHistory;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuBarJPanel;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
