/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.hospital;

import Hospital.CityDirectory;
import Hospital.Hospital;
import Hospital.HospitalDirectory;
import Hospital.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import ui.MainScreen;

/**
 *
 * @author hetal
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkAreaJPanel
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
    HospitalDirectory hospital_details;
    Hospital hospitalDemographicInfo;
    
    public HospitalWorkAreaJPanel(JPanel mainWorkArea, CityDirectory cityDirectory, HospitalDirectory hospital_details) {
        initComponents();
         this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
        this.hospital_details = hospital_details;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBarJPanel = new javax.swing.JPanel();
        btnAddHospitalInfo = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewHospital = new javax.swing.JButton();
        WorkAreaJPanel = new javax.swing.JPanel();

        menuBarJPanel.setBackground(new java.awt.Color(204, 204, 255));

        btnAddHospitalInfo.setForeground(new java.awt.Color(0, 102, 102));
        btnAddHospitalInfo.setText("Add Hospital");
        btnAddHospitalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalInfoActionPerformed(evt);
            }
        });

        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewHospital.setForeground(new java.awt.Color(0, 102, 102));
        btnViewHospital.setText("View Hospital");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPanelLayout = new javax.swing.GroupLayout(menuBarJPanel);
        menuBarJPanel.setLayout(menuBarJPanelLayout);
        menuBarJPanelLayout.setHorizontalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddHospitalInfo)
                    .addComponent(btnBack)
                    .addComponent(btnViewHospital))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBarJPanelLayout.setVerticalGroup(
            menuBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddHospitalInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewHospital)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menuBarJPanel);

        WorkAreaJPanel.setBackground(new java.awt.Color(204, 204, 255));
        WorkAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(WorkAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHospitalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalInfoActionPerformed
        // TODO add your handling code here:
        
        AddHospitalInfoJPanel apijp = new AddHospitalInfoJPanel(WorkAreaJPanel, cityDirectory);
        
        WorkAreaJPanel.add("AddCityJPanel", apijp);
        CardLayout layout = (CardLayout) WorkAreaJPanel.getLayout();
        layout.next(WorkAreaJPanel); 

    }//GEN-LAST:event_btnAddHospitalInfoActionPerformed

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        ViewHospitalJPanel p= new ViewHospitalJPanel(WorkAreaJPanel,cityDirectory,hospital_details);
        //ViewHospitalJPanel ptjp = new ViewHospitalJPanel(WorkAreaJPanel, cityDirectory, hospital_details);
        WorkAreaJPanel.add("PatientTableJPanel", p);
        CardLayout layout = (CardLayout) WorkAreaJPanel.getLayout();
        layout.next(WorkAreaJPanel);
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);

        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainScreen loginPanel = (MainScreen) component;
        //        loginPanel.populateSupplierCombo();

        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WorkAreaJPanel;
    private javax.swing.JButton btnAddHospitalInfo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuBarJPanel;
    // End of variables declaration//GEN-END:variables
}
