/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.hospital;

import Hospital.CityDirectory;
import Hospital.Hospital;
import Hospital.HospitalDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hetal
 */
public class ViewHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHospitalJPanel
     */
    HospitalDirectory hospital_details;
    Hospital hospitalDemographics;
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
    
    public ViewHospitalJPanel(JPanel WorkAreaJPanel,CityDirectory cityDirectory,HospitalDirectory hospital_details) {
        initComponents();
        this.cityDirectory=cityDirectory;
        this.mainWorkArea=mainWorkArea;
        this.hospital_details= hospital_details; 
        this.hospitalDemographics = hospitalDemographics;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewHospital = new javax.swing.JButton();
        btnUpdateHospital = new javax.swing.JButton();
        btnDeleteHospital = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearchHospital = new javax.swing.JTextField();
        lblHospitalName = new javax.swing.JLabel();
        lblHospitalAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblPincode = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();

        jTextField2.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "City", "Community", "Pincode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnViewHospital.setText("View");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });

        btnUpdateHospital.setText("Update");
        btnUpdateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHospitalActionPerformed(evt);
            }
        });

        btnDeleteHospital.setText("Delete");
        btnDeleteHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHospitalActionPerformed(evt);
            }
        });

        lblSearch.setText("Search");

        txtSearchHospital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchHospitalKeyReleased(evt);
            }
        });

        lblHospitalName.setText("Hospital Name:");

        lblHospitalAddress.setText("Hospital Address:");

        lblCity.setText("City:");

        lblCommunity.setText("Community:");

        lblPincode.setText("Pincode:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblSearch)
                .addGap(27, 27, 27)
                .addComponent(txtSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewHospital)
                .addGap(40, 40, 40)
                .addComponent(btnUpdateHospital)
                .addGap(54, 54, 54)
                .addComponent(btnDeleteHospital)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addComponent(lblHospitalName)
                            .addComponent(lblHospitalAddress))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHospitalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtHospitalName)
                            .addComponent(txtCity))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCommunity)
                            .addComponent(lblPincode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtPincode))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHospital)
                    .addComponent(btnUpdateHospital)
                    .addComponent(btnDeleteHospital)
                    .addComponent(lblSearch)
                    .addComponent(txtSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalName)
                    .addComponent(lblCommunity)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalAddress)
                    .addComponent(lblPincode)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
         int i= jTable1.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this,"Error");
                    return;
        }
            DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
            Hospital hospitalInfo = (Hospital) model.getValueAt(i,0);
            //set the data in textfields on clicking view button:
            
            txtHospitalName.setText(hospitalInfo.getHospital_Name());
            txtPincode.setText(String.valueOf(hospitalInfo.getPincode()));
            txtHospitalAddress.setText(hospitalInfo.getAddress());
            txtCity.setText(hospitalInfo.getCity());
            txtCommunity.setText(hospitalInfo.getCommunity());
    
        
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnUpdateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHospitalActionPerformed
        // TODO add your handling code here:
        int i= jTable1.getSelectedRow();
        if(i<0){
           JOptionPane.showMessageDialog(null,"Error"); 
        }
        
        else{
            //Get the data for textfields:
            DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
            
            String HospitalName= txtHospitalName.getText();
            String Address= txtHospitalAddress.getText();
            String City= txtCity.getText();
            String Community= txtCommunity.getText();
            int Pincode= Integer.parseInt(txtPincode.getText());
            
            //set updated value on table row
            
            model.setValueAt(HospitalName, jTable1.getSelectedRow(),0);
            model.setValueAt(Address, jTable1.getSelectedRow(), 1);
            model.setValueAt(City,jTable1.getSelectedRow(), 2);
            model.setValueAt(Community,jTable1.getSelectedRow(),3);
            model.setValueAt(Pincode, jTable1.getSelectedRow(),4);
           
            // After successfully setting, display the data:
            JOptionPane.showMessageDialog(null,"Update Successful!");
 
        }
    }//GEN-LAST:event_btnUpdateHospitalActionPerformed

    private void btnDeleteHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHospitalActionPerformed
        // TODO add your handling code here:
        int i= jTable1.getSelectedRow();
        
        if(i<0){
            JOptionPane.showMessageDialog(null,"Error"); 
        }
        
        else{
            
            DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
            //Demographic demo = (Demographic) model.getValueAt(i,0);
            //previous_data.deleteEmployee(demo);
            
            //here j is variable of employee which is selected!
            String j= model.getValueAt(i,0).toString();
            hospital_details.getHospital_details().remove(i);
            model.removeRow(i);
            JOptionPane.showMessageDialog(null,"Hospital Deleted");
            
            populateTable();  
            //removing data textfield values from the display bars:
                txtHospitalName.setText("");
                txtHospitalAddress.setText("");
                txtCity.setText("");
                txtCommunity.setText("");
                txtPincode.setText("");
        }
    }//GEN-LAST:event_btnDeleteHospitalActionPerformed

    private void txtSearchHospitalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchHospitalKeyReleased
        // TODO add your handling code here:
        
        String l= txtSearchHospital.getText();
        filter(l);
    }//GEN-LAST:event_txtSearchHospitalKeyReleased

    private void filter(String l){
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(model); 
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(l));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteHospital;
    private javax.swing.JButton btnUpdateHospital;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblHospitalAddress;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHospitalAddress;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtSearchHospital;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        for(Hospital hospitalDemographics: hospital_details.getHospital_details()){
             Object[] row = new Object[6];
             row[0]= hospitalDemographics;
             row[1]=hospitalDemographics.getHospital_Name();
             row[2]=hospitalDemographics.getAddress();
             row[3]=hospitalDemographics.getCity();
             row[4]=hospitalDemographics.getCommunity();
             row[5]=hospitalDemographics.getPincode();
             
             model.addRow(row);
        }
        
}}
