/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Hospital.CityDirectory;
import Hospital.DoctorDirectory;
import Hospital.HospitalDirectory;
import Hospital.PatientDirectory;
import Hospital.PersonDirectory;
import ui.city.CityWorkAreaJPanel;
import ui.doctor.DoctorWorkAreaJPanel;
import ui.hospital.HospitalWorkAreaJPanel;
import ui.patient.PatientWorkAreaJPanel;
import ui.person.AddPersonInfoJPanel;
import ui.person.PersonWorkAreaJPanel;

/**
 *
 * @author dhruv
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    JPanel mainWorkArea;
    CityDirectory cityDirectory;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospital_details;
//    public LoginScreen() {
//        initComponents();
//    }

    public LoginScreen(JPanel mainWorkArea, CityDirectory cityDirectory, PersonDirectory personDirectory, PatientDirectory patientDirectory, DoctorDirectory doctorDirectory,HospitalDirectory hospital_details) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.cityDirectory = cityDirectory;
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.doctorDirectory = doctorDirectory;
        this.hospital_details = hospital_details;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPatientDirectory = new javax.swing.JButton();
        btnPersonDirectory = new javax.swing.JButton();
        btnCityAdmin2 = new javax.swing.JButton();
        btnViewData = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();

        btnPatientDirectory.setText("Patient Directory");
        btnPatientDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDirectoryActionPerformed(evt);
            }
        });

        btnPersonDirectory.setText("Person Directory");
        btnPersonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonDirectoryActionPerformed(evt);
            }
        });

        btnCityAdmin2.setText("City Admin");
        btnCityAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityAdmin2ActionPerformed(evt);
            }
        });

        btnViewData.setText("View Community Vitals");
        btnViewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataActionPerformed(evt);
            }
        });

        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btnPatientDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCityAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPersonDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCityAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPatientDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewData, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCityAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityAdmin2ActionPerformed
        // TODO add your handling code here:
        CityWorkAreaJPanel cwjp = new CityWorkAreaJPanel(mainWorkArea, cityDirectory);
        mainWorkArea.add("WordAreaJPanel", cwjp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnCityAdmin2ActionPerformed

    private void btnPersonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonDirectoryActionPerformed
        // TODO add your handling code here:
        PersonWorkAreaJPanel pwajp = new PersonWorkAreaJPanel(mainWorkArea, cityDirectory, personDirectory);
        mainWorkArea.add("PersonWorkAreaJPanel", pwajp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnPersonDirectoryActionPerformed

    private void btnPatientDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDirectoryActionPerformed
        // TODO add your handling code here:
        PatientWorkAreaJPanel pwajp = new PatientWorkAreaJPanel(mainWorkArea, cityDirectory, patientDirectory);
        mainWorkArea.add("PatientWorkAreaJPanel", pwajp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnPatientDirectoryActionPerformed

    private void btnViewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataActionPerformed
        // TODO add your handling code here:
        HospitalWorkAreaJPanel vcvijp = new HospitalWorkAreaJPanel(mainWorkArea, cityDirectory,hospital_details);
        mainWorkArea.add("ViewCommnityVitalInfoJPanel", vcvijp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
        
    }//GEN-LAST:event_btnViewDataActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        DoctorWorkAreaJPanel vcvijp = new DoctorWorkAreaJPanel(mainWorkArea, cityDirectory, doctorDirectory);
        mainWorkArea.add("ViewCommnityVitalInfoJPanel", vcvijp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCityAdmin2;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnPatientDirectory;
    private javax.swing.JButton btnPersonDirectory;
    private javax.swing.JButton btnViewData;
    // End of variables declaration//GEN-END:variables
}
